{% set version = '0.5.9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clues
  version: {{ version|replace("-", "_") }}

source:
  fn: clues_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/clues_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/clues/clues_{{ version }}.tar.gz

  sha256: 1e6a986cb2a90a343aff625774e071b536c8de923373cdc49dbc7c5bddd2d47e

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('clues')"  # [not win]
    - "\"%R%\" -e \"library('clues')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=clues
  license: GPL (>= 2)
  summary: We developed the clues R package to provide functions  for automatically estimating
    the number of clusters and  getting the final cluster partition without any input  parameter
    except the stopping rule for convergence.  The package also provides functions to
    evaluate and compare the performances of partitions of a data set both numerically
    and graphically.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
