appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RGLo4wgwNTk41XFvvG2bPLFlK5WftE25y3bBTCBszQSIp1O/ZCm4qLRrjAI9AKNA2WVcGqkebKQnCS3XBZ910CYRYSoITXoTpq6O0ZajYlXS27EW6MfwrsSrMm2opn4V/wnMGoqcuoWr9fYnIegZEeNsDdlbZ9tKc4p+de3RIykaP5JKQd8112rrH4kHkam1JGpjm6/LVVHecamjv3o2ROJWQZbeWr9x3izzw5lcSXsbTLWm7ycnGjbVmWMeyD+1Zqx5dMsmYlUja9aIOrt1fsIJRuuGaDECneUBBkjSiiWE0WygZLsRlBG121yiXSTlC63M53xlE7ADNajcIkfMAic3aDXijziwm3M67eutPb3P9on3yFfRU+NbRdXjPaC0d9HMFsPnmWWF6r7KUle/MkdsnfkROJqIH8HRFcEI0bPKlefbzAK08hh8OaT7jFE7Jf9wKixbPc2P2sLTOcZEZUAzD4/Yq2UTveGvgfXtQeSF9PekQkcCA2epkN492Ryua5FuIazQt++pp8sF7ug/NUmpyId5uMONiGGSTtN20S4SJugjv644brO2a7iEedBsvcYsL926oyavc2g1cqGgD6bwrWUaSiIaljr/UfcFGwHEJBmkBOpiBvFT+qXbFkr5tB3B2Wz17Cq/SVx69sVjokFBdOCWo04kCYMdsnakEfE=}
