travis:
  secure:
    BINSTAR_TOKEN: CS7P+o+f1ZALqSxFWoXF2TGTpHkQCrOt98ZuVmFrZUqGZ8M9YvqTc1D5v56cO4eAoZof3EJeZOR61G8GfXjPJUmA1klQoHyPIZRCVQfIy15JZWZrOPUWI7RKyFgzon1Fx2Wm2i5afxYV8d3ZHvBTMK59QwU+NB583CB/dMHs4JD25qZpDArCqG/rCXWYgBQqPEZyeayxYF1aujUb03DK5VtySqG17sMRbhuF4cERPtx7Dc/NJMg+XRGBMAJFs6N4/BDgN+HhY5hq5ct/Y5wV2E86trUHygL0zy/FfUag6FYXdaSmE9khmg/5FlJiIY1gKrwCcPMtXw1T2jCIo5aMXsJRYHp/ePy2BqNyPpp+9YeWTUUENvOValdGCq2947+DXYEyQ5ai7f9xXRKUyTvk8SiR212lMQrcdh/q0bsbErRrY5hJKZuFBC1YaxGOkpBYjxse7r1/bpe1mZoc0c0mjbAILSUuoSwh1ZekVAfJzvFVVXpUxRjPke0sjZ5ESQ34r0eLBNcG72BI8iHbv6TEtZ8ki2QdLQQQJuyvl3xTN8NE0szVRtk0RVAs+fAojfV8TlxyrQWG3vtKCfWuAtFKPvXq9zZ9q9FP0zajRkCScShb/lNbBeiLNa68f1iRunRflfY+kNfAYhZoTWSv1KzJ2L3ige+GK35gS6vCRl7Tf9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
